### ISSUE TITLE
Detect  Anomaly on my own dataset

### ISSUE THREAD

**Issue by sundyCoder** [LeeDoYup/AnoGAN#11]
I want to train the GAN on my own dataset, after training for about 1000 epochs, the score of abnormal data don't have a gap  with normal data. Can you give me some comments about the training tricks?

**Comment by LK1711** [comment]
Hello @sundyCoder , how did you get the code workign on your dataset? I am trying the same but it is throwing value error for me: 

`ValueError: Trying to share variable discriminator/d_h2_lin/Matrix, but specified shape (23050, 1024) and found shape (65620, 1024).`

could you please give a me a small summary of what steps you did to get the rep running?
Thank you in advance!

**Comment by lzzlxxlsz** [comment]
excuse me, have you ever run the author's code successfully?

**Comment by LK1711** [comment]
> excuse me, have you ever run the author's code successfully?

yes, it works for me after I adjusted it to my data :)

**Comment by lzzlxxlsz** [comment]
if I  want to train my dataset ,and I have to put my data under the folder of data(exmple my data is a).then I just run the main.py .is right?

**Comment by lzzlxxlsz** [comment]
and how does your picture size ?

At 2019-03-07 19:57:57, "LK1711" <notifications@github.com> wrote:


excuse me, have you ever run the author's code successfully?

yes, it works for me after I adjusted it to my data :)

**Comment by lzzlxxlsz** [comment]
With the author's dataset,and should I run the code with python main.py --dataset test_01 --input_fname_pattern="*.png" --input_height=108 --crop --anomaly_test when I do the anomaly test?

**Comment by LK1711** [comment]
> if I  want to train my dataset ,and I have to put my data under the folder of data(exmple my data is a).then I just run the main.py .is right?

my command for my dataset (Surface) was:
python main.py --dataset Surface --train

**Comment by LK1711** [comment]
> With the author's dataset,and should I run the code with python main.py --dataset test_01 --input_fname_pattern="*.png" --input_height=108 --crop --anomaly_test when I do the anomaly test?

Once you have trained the model, then you run the anomaly test by:

python main.py --anomaly_test

**Comment by lzzlxxlsz** [comment]
> > With the author's dataset,and should I run the code with python main.py --dataset test_01 --input_fname_pattern="*.png" --input_height=108 --crop --anomaly_test when I do the anomaly test?
> 
> Once you have trained the model, then you run the anomaly test by:
> 
> python main.py --anomaly_test

OK，thanks，and for the size of dataset ,when I use my dataset(size :2450*2050),the input_height and output_height are 80,108,but the generated picture are so blurred,and seems like the same color.Is there the relation with the size of the original dataset ,thanks

**Comment by lzzlxxlsz** [comment]
> > excuse me, have you ever run the author's code successfully?
> 
> yes, it works for me after I adjusted it to my data :)

hello，I use my data to train a modle first,but the generated picture are so blurred,and seems like the same color.and do you know this error?thanks

**Comment by lzzlxxlsz** [comment]
Excuse me,and how dose your anomaly_test result for your dataset?is it fine?and how dose your anomaly_test result for the celebA dataset?

**Comment by lzzlxxlsz** [comment]
I want to ask you that the result of the celebA when you use the author's dataset ,is there some difference between the test image and generated images .Is the generated image similar to the test image?

**Comment by lzzlxxlsz** [comment]
hello, is the test result good for your dataset ?and is the generated image similar with the test data?
