### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by LK1711** [LeeDoYup/AnoGAN#14]
Hello,

how could we train on multiple GPUs? On my system it seems only one GPU is loaded. 

The configuration of my system is:
Ubuntu 16.04 LTS
2 x GeForce GTX 1080 8GB

Thank you in advance!

**Comment by LeeDoYup** [comment]
MultiGPU codes are not implemented in this repo.

**Comment by LeeDoYup** [comment]
You can change the training codes with following tutorial:
https://www.tensorflow.org/guide/using_gpu
