### ISSUE TITLE
Code to highlight the anomaly detected areas

### ISSUE THREAD

**Issue by vinodrajendran001** [LeeDoYup/AnoGAN#2]
Could you please tell me how to highlight the anomaly detected regions (red color) for X-ray unseen images like you demonstrated in the readme ?

Thanks.

**Comment by LeeDoYup** [comment]
In this implementation, I summed up reconstruction error of RGB pixel and anomaly regions were represented using gray image. If you want to represent anomaly regions with red color, use R channel in RGB image of reconstruction error.

**Comment by maryam089** [comment]
538 : scipy.misc.imsave(os.path.join(path,filename[1]),errors) this line ? @LeeDoYup

**Comment by lzzlxxlsz** [comment]
hello,have you finished it?and you want to mark the anomal-area?

**Comment by lzzlxxlsz** [comment]
> In this implementation, I summed up reconstruction error of RGB pixel and anomaly regions were represented using gray image. If you want to represent anomaly regions with red color, use R channel in RGB image of reconstruction error.

can you explain more concretely？and which code is setting it?

**Comment by LK1711** [comment]
Did anyone get this working? @maryam089 @lzzlxxlsz

**Comment by lipikak17** [comment]
@LeeDoYup could you please give a concrete explanation as to how this was done?

**Comment by lzzlxxlsz** [comment]
hello.I want to know that dose the generated image similar with the test data?
