### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sattlegger** [LeeDoYup/AnoGAN#29]
In your acknowledgements, you write: "Thanks for @carpedm20 's implementation of DCGAN. I implemented AnoGAN based on his implementation."

DCGAN is published under MIT license. https://github.com/carpedm20/DCGAN-tensorflow/blob/master/LICENSE

Please update the license of your repository because otherwise it is unclear for others to license their product which may be based on your code.

**Comment by LeeDoYup** [comment]
I am sincerely thanks to you let me know about the license.
I updated it.

**Comment by sattlegger** [comment]
Wow, that was quick! :) 
Btw, thank you for this repository. It saved us a lot of work.

**Comment by LeeDoYup** [comment]
I am happy if my works help you.
I expect your awesome project.
