### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by Jihunlee326** [LeeDoYup/AnoGAN#3]
(tensorflow) cardiac@cardiac-All-Series:~/AnoGAN$ python main.py --dataset=celebA input_height=108 --train
  File "main.py", line 115
    test_input = np.expand_dims(dcgan.test_data[idx],axis=0)
                                                           ^
TabError: inconsistent use of tabs and spaces in indentation

After running main.py, I simply get the "TabError". Can you point me to how to solve it is?

**Comment by LeeDoYup** [comment]
please check whether there is a strange indentation or other variation from original code in line 115 of main.py.
The program run well .
