### ISSUE TITLE
At train AnoGAN with MNIST data, Does the train set and test set all contain only normal data?

### ISSUE THREAD

**Issue by bemoregt** [LeeDoYup/AnoGAN#6]
Hi, @LeeDoYup 

In the case of Anomaly Gan, I knew that it trained with only normal datasets.

At train AnoGAN with MNIST data, Does the train set and test set all contain only normal data?

Or are both normal + abnormal divided into folders?
I wonder.

form @bemoregt.

**Comment by bemoregt** [comment]
도엽님, 감사합니다.

그러면 님의 아노갠에는 최대 이미지 사이즈가 얼마까지 들어가나요?

256x256 ??

from @bemoregt

**Comment by LeeDoYup** [comment]
The input image is ~~**resized**~~ into 64 x 64 image.
