### ISSUE TITLE
How files in checkpoint are created ?

### ISSUE THREAD

**Issue by maryam089** [LeeDoYup/AnoGAN#7]
I am working on a problem that my dataset is divided in subsets of 10. So what i need to do is train each subset of data with few epoches then stop training and again start the training process by replacing the previous subset of data with new one. Now the problem is that in the final or last model file in checkpoint does not contain any information of training data of previous subsets of dataset i trained it on but contain information on only the subset of dataset i trained at the end ........ So my question is ... Isn't model file should contain all info of all subsets of dataset i trained on? 

The problem is related to additional training on already trained data....
Please help  @LeeDoYup

**Comment by maryam089** [comment]
https://github.com/LeeDoYup/AnoGAN/blob/d7b16043212e3323f6ae9a7757c24bdfff8ef6ec/model.py#L262
That line says that a file in check point is saved after 100 steps

**Comment by LeeDoYup** [comment]
You can change the part of code as you want.
